export const BASE_STYLE_ALLOWLIST = [
  "display",
  "position",
  "inset",
  "inset-block-start",
  "inset-block-end",
  "inset-inline-start",
  "inset-inline-end",
  "top",
  "right",
  "bottom",
  "left",
  "z-index",
  "box-sizing",
  "overflow-x",
  "overflow-y",
  "contain",
  "isolation",
  "width",
  "height",
  "min-width",
  "max-width",
  "min-height",
  "max-height",
  "aspect-ratio",
  "flex-direction",
  "flex-wrap",
  "flex-grow",
  "flex-shrink",
  "flex-basis",
  "justify-content",
  "align-items",
  "align-content",
  "align-self",
  "gap",
  "row-gap",
  "column-gap",
  "grid-template-columns",
  "grid-template-rows",
  "grid-auto-flow",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "border-top-width",
  "border-right-width",
  "border-bottom-width",
  "border-left-width",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-bottom-right-radius",
  "border-bottom-left-radius",
  "font-family",
  "font-size",
  "font-weight",
  "line-height",
  "letter-spacing",
  "text-align",
  "white-space",
  "overflow-wrap",
  "word-break",
  "text-overflow",
  "visibility",
  "opacity",
  "content-visibility",
  "pointer-events",
  "clip-path",
  "transform",
] as const;

export const COLOR_STYLE_ALLOWLIST = ["color", "background-color", "border-color"] as const;

export function styleAllowlist(includeColors: boolean): readonly string[] {
  return includeColors ? [...BASE_STYLE_ALLOWLIST, ...COLOR_STYLE_ALLOWLIST] : BASE_STYLE_ALLOWLIST;
}

export function isAllowedStyleProperty(value: string, includeColors: boolean): boolean {
  return styleAllowlist(includeColors).includes(value);
}
