import {
  COLLECTOR_ID,
  COLLECTOR_VERSION,
  SCHEMA_VERSION,
  type CaptureConfiguration,
  type CaptureSession,
  type RuntimeSnapshot,
  type ElementMeasurement,
} from "../../src/domain/model";

export const sessionId = "123e4567-e89b-42d3-a456-426614174000";
export const snapshotId = "223e4567-e89b-42d3-a456-426614174000";
export const observationSetId = "323e4567-e89b-42d3-a456-426614174000";
export const capturedAt = "2026-06-13T10:00:00.000Z";
export const hashA = `sha256:${"a".repeat(64)}` as const;
export const hashB = `sha256:${"b".repeat(64)}` as const;

export function makeSession(): CaptureSession {
  return {
    schema_id: "urn:edis:schema:browser:capture-session",
    schema_version: "1.1.0",
    artifact_type: "capture_session",
    producer: { product: "EDIS Browser Runtime Evidence Collector", version: COLLECTOR_VERSION },
    captured_at: capturedAt,
    canonicalization: { profile: "EDIS-CJ-1", hash_algorithm: "sha256" },
    data: {
      session_id: sessionId,
      observation_set_id: observationSetId,
      name: "Test session",
      created_at: capturedAt,
      extension_version: COLLECTOR_VERSION,
      browser_family: "Chrome",
      browser_version: "116",
      runtime_environment: {
        browser_family: "Chrome",
        browser_version: "116",
        platform_category: "DESKTOP",
      },
      source_context_reference: null,
      source_binding_state: "UNMATCHED",
      workflow_mode: "RUNTIME_EVIDENCE",
      captures: [
        {
          snapshot_id: snapshotId,
          label: "Desktop",
          captured_at: capturedAt,
          actual_width: 1280,
          actual_height: 720,
          page_context_id: hashA,
          page_fingerprint: hashB,
          page_binding_state: "UNMATCHED",
          page_binding_reason_codes: ["SOURCE_CONTEXT_NOT_IMPORTED"],
          source_document_id: null,
          source_document_type: null,
          source_document_count: 0,
          source_section_count: 0,
          source_widget_count: 0,
          runtime_region_count: 0,
          runtime_section_region_count: 0,
          runtime_container_region_count: 0,
          runtime_widget_marker_count: 0,
          exact_binding_count: 0,
          probable_binding_count: 0,
          ambiguous_binding_count: 0,
          unmatched_runtime_node_count: 0,
          element_count: 0,
          overflow_count: 0,
          diagnostic_count: 0,
          screenshot_available: false,
          completeness_status: "COMPLETE",
          partial_reasons: [],
          truncated_branch_count: 0,
          identity_collision_count: 0,
          skipped_hidden_subtree_count: 0,
          capture_environment_warning_count: 0,
          status: "COMPLETE",
        },
      ],
      status: "COMPLETE",
    },
    diagnostics: [],
  };
}

export function makeCaptureConfiguration(): CaptureConfiguration {
  return {
    schemaVersion: 4,
    captureProfile: "STANDARD",
    captureIntent: "GENERAL_AUDIT",
    redactionMode: "STRICT",
    includeScreenshot: false,
    includeHiddenElements: false,
    includePath: false,
    includePageTitle: false,
    includeColors: false,
    includeTextPreview: false,
    includeTextShape: true,
    includeInteractionFacts: true,
    includeRelationshipGraph: true,
    prepareFullDocumentImages: false,
    readinessHardTimeoutMs: 500,
    maxTextPreviewChars: 160,
    retainAfterExport: false,
    maxElements: 750,
    maxDepth: 24,
    maxSnapshotBytes: 12_000_000,
    sessionId,
    snapshotId,
    observationIndex: 0,
    userLabel: "Desktop",
    evidenceLabel: "USER_LABELED_VIEWPORT",
    requestedProfileId: "DESKTOP",
    workflowMode: "RUNTIME_EVIDENCE",
    expectedPageFingerprint: null,
    expectedViewportWidth: null,
    capturedAt,
    bindingContext: null,
  };
}

export function makeElementMeasurement(order = 0): ElementMeasurement {
  const nodeId = `node-${String(order + 1).padStart(6, "0")}`;
  return {
    node_id: nodeId,
    document_order: order,
    evidence_lineage: {
      page_context_id: hashA,
      snapshot_id: snapshotId,
      runtime_node_id: nodeId,
      source_document_id: null,
      source_document_type: null,
      source_element_key: null,
      source_section_key: null,
      binding_state: "UNMATCHED",
    },
    identity: {
      tag_name: "div",
      role: null,
      class_tokens: [],
      stable_dom_reference: `html:nth-of-type(1)>body:nth-of-type(1)>div:nth-of-type(${order + 1})`,
      reference_sha256: hashA,
      sibling_index: order,
      identity_source: "STRUCTURAL_PATH",
      identity_strategy: "STABLE_DOM_REFERENCE",
      identity_confidence: "PROBABLE",
      identity_status: "UNIQUE",
      unique_in_document: true,
      reference_occurrence_count: 1,
      collision_count: 0,
    },
    runtime_elementor_markers: {
      data_elementor_id: null,
      data_id: null,
      elementor_class_marker_present: false,
      widget_class_markers: [],
      structure_class_markers: [],
    },
    source_binding: {
      availability: "UNAVAILABLE",
      binding_state: "UNMATCHED",
      binding_basis: "NO_SOURCE_CONTEXT",
      page_elementor_document_id: null,
      elementor_element_id: null,
      nearest_elementor_ancestor_id: null,
      elementor_ancestor_ids: [],
      runtime_id_occurrence_count: 0,
      source_id_occurrence_count: null,
      source_document_id: null,
      source_element_key: null,
      source_record_sha256: null,
      unique_in_runtime_document: false,
      unique_in_source_document: null,
      confirmation_state: "NOT_CONFIRMED",
      reason_codes: ["SOURCE_CONTEXT_NOT_IMPORTED"],
      source_document_type: null,
      source_element_kind: null,
      source_widget_type: null,
      source_architecture_kind: null,
      source_editor_label: null,
      source_editor_label_source: null,
      source_section_key: null,
      source_section_element_id: null,
      source_section_kind: null,
    },
    relationships: {
      dom_parent_reference: "html:nth-of-type(1)>body:nth-of-type(1)",
      dom_parent_reference_sha256: hashB,
      dom_parent_emitted: false,
      nearest_emitted_parent_node_id: null,
      nearest_positioned_ancestor_reference: null,
      nearest_positioned_ancestor_node_id: null,
      nearest_scroll_ancestor_reference: null,
      nearest_scroll_ancestor_node_id: null,
      nearest_clipping_ancestor_reference: null,
      nearest_clipping_ancestor_node_id: null,
      sibling_index: order,
      sibling_count: 1,
      child_element_count: 0,
      dom_depth: 2,
      availability: "AVAILABLE",
    },
    bounding_rect: { x: 0, y: 0, top: 0, right: 10, bottom: 10, left: 0, width: 10, height: 10 },
    document_coordinates: { x: 0, y: 0 },
    viewport_intersection: {
      intersects: true,
      ratio: 1,
      rect: { x: 0, y: 0, top: 0, right: 10, bottom: 10, left: 0, width: 10, height: 10 },
    },
    area: 100,
    positioning: "static",
    computed_styles: { display: "block" },
    visibility: {
      display: "block",
      visibility: "visible",
      opacity: 1,
      direct_hidden: false,
      hidden_by_ancestor: false,
      nearest_hidden_ancestor_reference: null,
      nearest_hidden_ancestor_node_id: null,
      rendered: true,
      effective_rendered: true,
      has_box: true,
      intersects_viewport: true,
    },
    overflow: {
      client_width: 10,
      client_height: 10,
      scroll_width: 10,
      scroll_height: 10,
      offset_width: 10,
      offset_height: 10,
      horizontal_overflow: false,
      vertical_overflow: false,
      clipped_by_ancestor: false,
    },
    interaction_facts: {
      availability: "NOT_APPLICABLE",
      tag_name: "div",
      role: null,
      native_interactive_kind: null,
      tab_index: null,
      disabled: false,
      aria_disabled: null,
      aria_expanded: null,
      aria_controls_present: false,
      href_present: false,
      input_type: null,
      contenteditable: false,
      pointer_events: "auto",
      cursor: "auto",
    },
    text_shape: {
      availability: "NOT_APPLICABLE",
      measurement_status: "NO_TEXT",
      measurement_method: "NONE",
      text_present: false,
      text_node_count: 0,
      grapheme_count: 0,
      word_count: 0,
      rendered_line_box_count: 0,
      longest_unbroken_token_length: 0,
      white_space: "normal",
      overflow_wrap: "normal",
      word_break: "normal",
      text_overflow: "clip",
      line_clamp: null,
      horizontal_clipping: false,
      vertical_clipping: false,
      preview: null,
      preview_truncated: false,
    },
    runtime_instance: {
      availability: "INSUFFICIENT",
      instance_state: "UNKNOWN",
      instance_group_id: null,
      instance_index: null,
      observed_instance_count: 0,
      source_element_key: null,
      source_document_id: null,
      instance_basis: "NO_VALIDATED_SOURCE_KEY",
      basis_evidence: ["RUNTIME_INSTANCE_NOT_EVALUATED"],
    },
    computed_style_origin: {
      availability: "INSUFFICIENT",
      observation_kind: "RESOLVED_COMPUTED_VALUE_ONLY",
      cssom_rule_inspection_performed: false,
      matched_rule_accessibility: "NOT_MEASURED",
      custom_property_reference_observation: "NOT_MEASURED",
    },
  };
}

export function makeSnapshot(): RuntimeSnapshot {
  return {
    schema_version: SCHEMA_VERSION,
    artifact_type: "runtime_snapshot",
    status: "AVAILABLE",
    source: { collector_id: COLLECTOR_ID, collector_version: COLLECTOR_VERSION },
    captured_at: capturedAt,
    snapshot_id: snapshotId,
    session_id: sessionId,
    observation_index: 0,
    capture_intent: "GENERAL_AUDIT",
    capture_configuration: {
      capture_profile: "STANDARD",
      max_elements: 750,
      max_depth: 24,
      max_snapshot_bytes: 12_000_000,
      include_hidden_elements: false,
      include_colors: false,
      include_text_shape: true,
      include_interaction_facts: true,
      include_relationship_graph: true,
      include_text_preview: false,
      text_preview_limit: 160,
      readiness_hard_timeout_ms: 500,
    },
    evidence_source: "PUBLISHED_FRONTEND",
    runtime_environment: {
      browser_family: "Chrome",
      browser_version: "116",
      platform_category: "DESKTOP",
    },
    source_context_reference: null,
    page: {
      page_context_id: hashA,
      origin: "https://example.test",
      path: null,
      title: null,
      document_language: "en",
      document_direction: "ltr",
      ready_state: "complete",
      visibility_state: "visible",
      browser_family: "Chrome",
      browser_version: "116",
      platform_category: "DESKTOP",
      locator_facts: null,
      locator_disclosure: "HASH_ONLY",
      page_locator_sha256: hashA,
      page_fingerprint: hashB,
      elementor: {
        page_marker_present: false,
        frontend_class_markers: [],
        raw_data_elementor_ids: [],
        page_elementor_document_id: null,
      },
      imported_site_fingerprint: null,
      page_binding_evidence: {
        availability: "INSUFFICIENT",
        binding_state: "UNMATCHED",
        source_document_id: null,
        source_document_fingerprint: null,
        page_locator_candidate_match: false,
        page_elementor_document_id: null,
        confirmation_state: "NOT_CONFIRMED",
        reason_codes: ["SOURCE_CONTEXT_NOT_IMPORTED"],
      },
      source_documents_present: [],
    },
    viewport: {
      inner_width: 1280,
      inner_height: 720,
      outer_width: 1280,
      outer_height: 800,
      device_pixel_ratio: 1,
      visual_viewport: { width: 1280, height: 720, scale: 1, offset_left: 0, offset_top: 0 },
      orientation: "landscape-primary",
      horizontal_scrollbar: false,
      vertical_scrollbar: true,
      zoom_evidence_status: "UNKNOWN",
      user_label: "Desktop",
      evidence_label: "USER_LABELED_VIEWPORT",
      requested_profile_id: "DESKTOP",
    },
    document_metrics: {
      document_scroll_width: 1280,
      document_scroll_height: 1400,
      document_client_width: 1280,
      document_client_height: 720,
      body_scroll_width: 1280,
      body_scroll_height: 1400,
      horizontal_page_overflow: false,
      vertical_scroll_exists: true,
      total_elementor_elements: 0,
      total_interactive_elements: 0,
      discovered_elementor_elements: 0,
      emitted_elementor_elements: 0,
      skipped_elementor_elements: 0,
      discovered_interactive_candidates: 0,
      emitted_interactive_candidates: 0,
      discovered_fixed_elements: 0,
      emitted_fixed_elements: 0,
      discovered_sticky_elements: 0,
      emitted_sticky_elements: 0,
      scanned_dom_nodes: 1,
      emitted_elements: 0,
      maximum_measured_depth: 0,
      truncated_branch_count: 0,
      fixed_elements: 0,
      sticky_elements: 0,
      skipped_hidden_subtree_count: 0,
      skipped_hidden_direct_child_count: 0,
    },
    capture_readiness: {
      availability: "AVAILABLE",
      process_state: "STABLE",
      document_ready_state: "complete",
      fonts_api_available: true,
      fonts_status: "loaded",
      incomplete_image_count: 0,
      incomplete_image_count_total: 0,
      incomplete_image_count_in_viewport: 0,
      viewport_image_readiness: {
        candidate_count: 0,
        loaded_count: 0,
        broken_count: 0,
        pending_count: 0,
        decode_failed_count: 0,
        timed_out_count: 0,
        wait_time_ms: 0,
        timeout_ms: 0,
        timeout_policy_id: "edis.viewport-image-readiness",
        timeout_policy_version: 1,
      },
      active_animation_count: 0,
      initial_document_width: 1280,
      final_document_width: 1280,
      initial_document_height: 1400,
      final_document_height: 1400,
      initial_viewport_width: 1280,
      final_viewport_width: 1280,
      initial_viewport_height: 720,
      final_viewport_height: 720,
      sample_count: 3,
      settle_duration_ms: 300,
      hard_timeout_ms: 500,
      timeout_reached: false,
    },
    capture_state: {
      scroll_x: 0,
      scroll_y: 0,
      document_visibility_state: "visible",
      document_prerendering: false,
      document_has_focus: true,
      active_element_reference_sha256: null,
      prefers_reduced_motion: false,
      pointer_capability: "FINE",
      hover_capability: "HOVER",
      animation_count: 0,
      sticky_candidate_count: 0,
      capture_trigger: "USER_INITIATED",
    },
    capture_environment: {
      wordpress_admin_bar_present: false,
      admin_bar: {
        body_admin_bar_class: false,
        wpadminbar_element_present: false,
        wpadminbar_computed_display: null,
        wpadminbar_computed_visibility: null,
        wpadminbar_rect_height: null,
        html_computed_margin_top: "0px",
        body_computed_margin_top: "0px",
        detection_state: "ABSENT",
      },
      elementor_editor_preview_present: false,
      iframe_capture: false,
      document_not_focused: false,
      page_not_at_top: false,
      open_html_dialog_count: 0,
      aria_modal_true_count: 0,
      body_pointer_events: "auto",
      visible_modal_count: 0,
      active_animations_present: false,
      incomplete_images_in_viewport: 0,
      viewport_image_readiness: {
        candidate_count: 0,
        loaded_count: 0,
        broken_count: 0,
        pending_count: 0,
        decode_failed_count: 0,
        timed_out_count: 0,
        wait_time_ms: 0,
        timeout_ms: 0,
        timeout_policy_id: "edis.viewport-image-readiness",
        timeout_policy_version: 1,
      },
      warning_codes: [],
    },
    capture_completeness: {
      status: "COMPLETE",
      reasons: [],
      capture_profile: "STANDARD",
      elements_visited: 1,
      elements_emitted: 0,
      maximum_depth_observed: 0,
      truncated_branch_count: 0,
      element_budget: 750,
      element_budget_used: 0,
      scan_budget: 15000,
      scan_budget_used: 1,
      identity_collision_count: 0,
      skipped_hidden_subtree_count: 0,
      skipped_hidden_direct_child_count: 0,
    },
    runtime_structure_sha256: hashA,
    runtime_regions: [],
    page_structure_summary: {
      source_document_count: 0,
      source_section_count: 0,
      source_widget_count: 0,
      runtime_region_count: 0,
      runtime_section_region_count: 0,
      runtime_container_region_count: 0,
      runtime_widget_marker_count: 0,
      exact_binding_count: 0,
      probable_binding_count: 0,
      ambiguous_binding_count: 0,
      unmatched_runtime_node_count: 0,
      document_instance_count: 0,
      repeated_runtime_instance_group_count: 0,
    },
    document_instances: [],
    source_runtime_cardinality: {
      availability: "INSUFFICIENT",
      source_elements_imported: 0,
      source_elements_with_zero_candidates: 0,
      source_elements_with_one_candidate: 0,
      source_elements_with_multiple_candidates: 0,
      runtime_nodes_without_source_candidate: 0,
      records: [],
    },
    elements: [],
    privacy: {
      redaction_mode: "STRICT",
      screenshot_requested: false,
      url_path_included: false,
      locator_facts_included: false,
      locator_path_disclosure: "HASH_ONLY",
      page_title_included: false,
      color_styles_included: false,
      text_preview_requested: false,
      text_preview_limit: 160,
    },
    diagnostics: [],
  };
}
